// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc1d1Zg0LDwA7Y2ijMFbJGjVIHSvOBQbk',
    appId: '1:856971602175:web:759e9106b947b0017244ca',
    messagingSenderId: '856971602175',
    projectId: 'duofit---2-in-1-fitness-app',
    authDomain: 'duofit---2-in-1-fitness-app.firebaseapp.com',
    storageBucket: 'duofit---2-in-1-fitness-app.appspot.com',
    measurementId: 'G-MH6LZ398PN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqwhXltu8_Smsqgza_1L4YmE1Nv-Zod4s',
    appId: '1:856971602175:android:213094bc41b9afea7244ca',
    messagingSenderId: '856971602175',
    projectId: 'duofit---2-in-1-fitness-app',
    storageBucket: 'duofit---2-in-1-fitness-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHDxEXWE9IbLO1cW9EsTUHgqYvRp9zbgQ',
    appId: '1:856971602175:ios:1fa41bdb7b6870857244ca',
    messagingSenderId: '856971602175',
    projectId: 'duofit---2-in-1-fitness-app',
    storageBucket: 'duofit---2-in-1-fitness-app.appspot.com',
    iosClientId: '856971602175-9b6j1gvgqb6pfc0g5m6l2vsiosc8bim6.apps.googleusercontent.com',
    iosBundleId: 'com.example.duoFit',
  );
}
